CREATE TABLE "users" (
	"id" uuid PRIMARY KEY,
	"username" varchar NOT NULL UNIQUE,
	"email" varchar NOT NULL UNIQUE,
	"password" varchar,
	"created_at" timestamp,
	"updated_at" timestamp,
	"country_code" int,
	"url" varchar,
	"company" varchar,     
	"received_events_url" varchar,
	"bio" varchar,          
	"type" varchar,              
	"gravatar_id" varchar,     
	"html_url"varchar, 
	"location"varchar, 
	"login" varchar,
	"name" varchar, 
	"node_id" varchar, 
	"organizations_url" varchar, 
	"avatar_url" varchar, 
	"oauth_id" int,
	"is_active" boolean,  
	"hireable" boolean
);
