// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/kone/github_actions/v1/build_project.proto

package github_actions_v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/containerish/OpenRegistry/services/kone/github_actions/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// GitHubActionsProjectServiceName is the fully-qualified name of the GitHubActionsProjectService
	// service.
	GitHubActionsProjectServiceName = "services.kone.github_actions.v1.GitHubActionsProjectService"
)

// GitHubActionsProjectServiceClient is a client for the
// services.kone.github_actions.v1.GitHubActionsProjectService service.
type GitHubActionsProjectServiceClient interface {
	CreateProject(context.Context, *connect_go.Request[v1.CreateProjectRequest]) (*connect_go.Response[v1.CreateProjectResponse], error)
	GetProject(context.Context, *connect_go.Request[v1.GetProjectRequest]) (*connect_go.Response[v1.GetProjectResponse], error)
	DeleteProject(context.Context, *connect_go.Request[v1.DeleteProjectRequest]) (*connect_go.Response[v1.DeleteProjectResponse], error)
	ListProjects(context.Context, *connect_go.Request[v1.ListProjectsRequest]) (*connect_go.Response[v1.ListProjectsResponse], error)
}

// NewGitHubActionsProjectServiceClient constructs a client for the
// services.kone.github_actions.v1.GitHubActionsProjectService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGitHubActionsProjectServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) GitHubActionsProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &gitHubActionsProjectServiceClient{
		createProject: connect_go.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+"/services.kone.github_actions.v1.GitHubActionsProjectService/CreateProject",
			opts...,
		),
		getProject: connect_go.NewClient[v1.GetProjectRequest, v1.GetProjectResponse](
			httpClient,
			baseURL+"/services.kone.github_actions.v1.GitHubActionsProjectService/GetProject",
			opts...,
		),
		deleteProject: connect_go.NewClient[v1.DeleteProjectRequest, v1.DeleteProjectResponse](
			httpClient,
			baseURL+"/services.kone.github_actions.v1.GitHubActionsProjectService/DeleteProject",
			opts...,
		),
		listProjects: connect_go.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+"/services.kone.github_actions.v1.GitHubActionsProjectService/ListProjects",
			opts...,
		),
	}
}

// gitHubActionsProjectServiceClient implements GitHubActionsProjectServiceClient.
type gitHubActionsProjectServiceClient struct {
	createProject *connect_go.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	getProject    *connect_go.Client[v1.GetProjectRequest, v1.GetProjectResponse]
	deleteProject *connect_go.Client[v1.DeleteProjectRequest, v1.DeleteProjectResponse]
	listProjects  *connect_go.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
}

// CreateProject calls services.kone.github_actions.v1.GitHubActionsProjectService.CreateProject.
func (c *gitHubActionsProjectServiceClient) CreateProject(ctx context.Context, req *connect_go.Request[v1.CreateProjectRequest]) (*connect_go.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// GetProject calls services.kone.github_actions.v1.GitHubActionsProjectService.GetProject.
func (c *gitHubActionsProjectServiceClient) GetProject(ctx context.Context, req *connect_go.Request[v1.GetProjectRequest]) (*connect_go.Response[v1.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// DeleteProject calls services.kone.github_actions.v1.GitHubActionsProjectService.DeleteProject.
func (c *gitHubActionsProjectServiceClient) DeleteProject(ctx context.Context, req *connect_go.Request[v1.DeleteProjectRequest]) (*connect_go.Response[v1.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// ListProjects calls services.kone.github_actions.v1.GitHubActionsProjectService.ListProjects.
func (c *gitHubActionsProjectServiceClient) ListProjects(ctx context.Context, req *connect_go.Request[v1.ListProjectsRequest]) (*connect_go.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// GitHubActionsProjectServiceHandler is an implementation of the
// services.kone.github_actions.v1.GitHubActionsProjectService service.
type GitHubActionsProjectServiceHandler interface {
	CreateProject(context.Context, *connect_go.Request[v1.CreateProjectRequest]) (*connect_go.Response[v1.CreateProjectResponse], error)
	GetProject(context.Context, *connect_go.Request[v1.GetProjectRequest]) (*connect_go.Response[v1.GetProjectResponse], error)
	DeleteProject(context.Context, *connect_go.Request[v1.DeleteProjectRequest]) (*connect_go.Response[v1.DeleteProjectResponse], error)
	ListProjects(context.Context, *connect_go.Request[v1.ListProjectsRequest]) (*connect_go.Response[v1.ListProjectsResponse], error)
}

// NewGitHubActionsProjectServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGitHubActionsProjectServiceHandler(svc GitHubActionsProjectServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/services.kone.github_actions.v1.GitHubActionsProjectService/CreateProject", connect_go.NewUnaryHandler(
		"/services.kone.github_actions.v1.GitHubActionsProjectService/CreateProject",
		svc.CreateProject,
		opts...,
	))
	mux.Handle("/services.kone.github_actions.v1.GitHubActionsProjectService/GetProject", connect_go.NewUnaryHandler(
		"/services.kone.github_actions.v1.GitHubActionsProjectService/GetProject",
		svc.GetProject,
		opts...,
	))
	mux.Handle("/services.kone.github_actions.v1.GitHubActionsProjectService/DeleteProject", connect_go.NewUnaryHandler(
		"/services.kone.github_actions.v1.GitHubActionsProjectService/DeleteProject",
		svc.DeleteProject,
		opts...,
	))
	mux.Handle("/services.kone.github_actions.v1.GitHubActionsProjectService/ListProjects", connect_go.NewUnaryHandler(
		"/services.kone.github_actions.v1.GitHubActionsProjectService/ListProjects",
		svc.ListProjects,
		opts...,
	))
	return "/services.kone.github_actions.v1.GitHubActionsProjectService/", mux
}

// UnimplementedGitHubActionsProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGitHubActionsProjectServiceHandler struct{}

func (UnimplementedGitHubActionsProjectServiceHandler) CreateProject(context.Context, *connect_go.Request[v1.CreateProjectRequest]) (*connect_go.Response[v1.CreateProjectResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("services.kone.github_actions.v1.GitHubActionsProjectService.CreateProject is not implemented"))
}

func (UnimplementedGitHubActionsProjectServiceHandler) GetProject(context.Context, *connect_go.Request[v1.GetProjectRequest]) (*connect_go.Response[v1.GetProjectResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("services.kone.github_actions.v1.GitHubActionsProjectService.GetProject is not implemented"))
}

func (UnimplementedGitHubActionsProjectServiceHandler) DeleteProject(context.Context, *connect_go.Request[v1.DeleteProjectRequest]) (*connect_go.Response[v1.DeleteProjectResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("services.kone.github_actions.v1.GitHubActionsProjectService.DeleteProject is not implemented"))
}

func (UnimplementedGitHubActionsProjectServiceHandler) ListProjects(context.Context, *connect_go.Request[v1.ListProjectsRequest]) (*connect_go.Response[v1.ListProjectsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("services.kone.github_actions.v1.GitHubActionsProjectService.ListProjects is not implemented"))
}
