name: "Dispatch workflows"
on: push

concurrency: 
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  call-lint:
    name: "Lint"
    uses: ./.github/workflows/golangci-lint.yml


  ## Storj S3 Gateway Tests
  call-storj-s3-image-push:
    name: OCI - Storj S3
    uses: ./.github/workflows/oci-dist-spec-storj-s3-push.yml
    secrets: inherit
    needs:
      - call-lint
  call-storj-s3-image-pull:
    name: OCI - Storj S3
    uses: ./.github/workflows/oci-dist-spec-storj-s3-pull.yml
    secrets: inherit
    needs:
      - call-lint
  call-storj-s3-image-content-discovery:
    name: OCI - Storj S3
    uses: ./.github/workflows/oci-dist-spec-storj-s3-content-discovery.yml
    secrets: inherit
    needs:
      - call-lint
  call-storj-s3-image-content-management:
    name: OCI - Storj S3
    uses: ./.github/workflows/oci-dist-spec-storj-s3-content-management.yml
    secrets: inherit
    needs:
      - call-lint


  ## Storj Uplink Tests
  call-storj-uplink-image-push:
    name: OCI - Storj Uplink
    uses: ./.github/workflows/oci-dist-spec-storj-uplink-push.yml
    secrets: inherit
    needs:
      - call-lint
  call-storj-uplink-image-pull:
    name: OCI - Storj Uplink
    uses: ./.github/workflows/oci-dist-spec-storj-uplink-pull.yml
    secrets: inherit
    needs:
      - call-lint
  call-storj-uplink-image-content-discovery:
    name: OCI - Storj Uplink
    uses: ./.github/workflows/oci-dist-spec-storj-uplink-content-discovery.yml
    secrets: inherit
    needs:
      - call-lint
  call-storj-uplink-image-content-management:
    name: OCI - Storj Uplink
    uses: ./.github/workflows/oci-dist-spec-storj-uplink-content-management.yml
    secrets: inherit
    needs:
      - call-lint


  ## Filebase Tests
  call-filebase-image-push:
    name: OCI - Filebase + IPFS
    uses: ./.github/workflows/oci-dist-spec-filebase-push.yml
    secrets: inherit
    needs:
      - call-lint
  call-filebase-image-pull:
    name: OCI - Filebase + IPFS
    uses: ./.github/workflows/oci-dist-spec-filebase-pull.yml
    secrets: inherit
    needs:
      - call-lint
  call-filebase-image-content-discovery:
    name: OCI - Filebase + IPFS
    uses: ./.github/workflows/oci-dist-spec-filebase-content-discovery.yml
    secrets: inherit
    needs:
      - call-lint
  call-filebase-image-content-management:
    name: OCI - Filebase + IPFS
    uses: ./.github/workflows/oci-dist-spec-filebase-content-management.yml
    secrets: inherit
    needs:
      - call-lint
